name: codedreamers-app

services:
  - name: angular-service
    image:
      name: docker.io/Samu345/HabitTracker
      source:
        git:
          url: https://github.com/Samue45/HabitTracker.git
          branch: main
          build_command: docker build -t Samue45/HabitTracker .
          registry: docker.io
    ports:
      - port: 80
        protocol: HTTP
