services:
  - type: web
    name: habittracker-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    buildCommand: npm install && npm run build
    startCommand: http-server dist/tu-app-angular
